type Weapon = {
  name: string;
  id: string;
  category: string;
};

export const weapons: Weapon[] = [
  { name: "Pistol Mk II", id: "WEAPON_PISTOL_MK2", category: "Handgun" },
  { name: "Snowball", id: "WEAPON_SNOWBALL", category: "Thrown" },
  { name: "Assault SMG", id: "WEAPON_ASSAULTSMG", category: "SMG" },
  { name: "Molotov", id: "WEAPON_MOLOTOV", category: "Thrown" },
  { name: "SMG Mk II", id: "WEAPON_SMG_MK2", category: "SMG" },
  { name: "Pool Cue", id: "WEAPON_POOLCUE", category: "Melee" },
  { name: "Grenade", id: "WEAPON_GRENADE", category: "Thrown" },
  { name: "Marksman Pistol", id: "WEAPON_MARKSMANPISTOL", category: "Handgun" },
  { name: "Bullpup Shotgun", id: "WEAPON_BULLPUPSHOTGUN", category: "Shotgun" },
  { name: "Parachute", id: "GADGET_PARACHUTE", category: "Gadget" },
  { name: "Bottle", id: "WEAPON_BOTTLE", category: "Melee" },
  { name: "Combat MG", id: "WEAPON_COMBATMG", category: "Machine Gun" },
  { name: "Mini SMG", id: "WEAPON_MINISMG", category: "SMG" },
  { name: "Sweeper Shotgun", id: "WEAPON_SWEEPERSHOTGUN", category: "Shotgun" },
  { name: "Assault Rifle Mk II", id: "WEAPON_ASSAULTRIFLE_MK2", category: "Assault Rifle" },
  { name: "Carbine Rifle Mk II", id: "WEAPON_CARBINERIFLE_MK2", category: "Assault Rifle" },
  { name: "Baseball Bat", id: "WEAPON_BAT", category: "Melee" },
  { name: "Heavy Sniper Mk II", id: "WEAPON_HEAVYSNIPER_MK2", category: "Sniper" },
  { name: "Ball", id: "WEAPON_BALL", category: "Thrown" },
  { name: "Pump Shotgun Mk II", id: "WEAPON_PUMPSHOTGUN_MK2", category: "Shotgun" },
  { name: "Flashlight", id: "WEAPON_FLASHLIGHT", category: "Melee" },
  { name: "Combat PDW", id: "WEAPON_COMBATPDW", category: "SMG" },
  { name: "Combat Pistol", id: "WEAPON_COMBATPISTOL", category: "Handgun" },
  { name: "SNS Pistol Mk II", id: "WEAPON_SNSPISTOL_MK2", category: "Handgun" },
  { name: "Firework Launcher", id: "WEAPON_FIREWORK", category: "Launcher" },
  { name: "Compact Rifle", id: "WEAPON_COMPACTRIFLE", category: "Assault Rifle" },
  { name: "Machine Pistol", id: "WEAPON_MACHINEPISTOL", category: "SMG" },
  { name: "Marksman Rifle", id: "WEAPON_MARKSMANRIFLE", category: "Sniper" },
  { name: "Auto Shotgun", id: "WEAPON_AUTOSHOTGUN", category: "Shotgun" },
  { name: "Proximity Mine", id: "WEAPON_PROXMINE", category: "Thrown" },
  { name: "Revolver", id: "WEAPON_REVOLVER", category: "Handgun" },
  { name: "Combat Shotgun", id: "WEAPON_COMBATSHOTGUN", category: "Shotgun" },
  { name: "Military Rifle", id: "WEAPON_MILITARYRIFLE", category: "Assault Rifle" },
  { name: "Unholy Hellbringer", id: "WEAPON_RAYCARBINE", category: "Special" },
  { name: "Bullpup Rifle", id: "WEAPON_BULLPUPRIFLE", category: "Assault Rifle" },
  { name: "Gusenberg Sweeper", id: "WEAPON_GUSENBERG", category: "SMG" },
  { name: "Heavy Shotgun", id: "WEAPON_HEAVYSHOTGUN", category: "Shotgun" },
  { name: "Flare", id: "WEAPON_FLARE", category: "Thrown" },
  { name: "Knife", id: "WEAPON_KNIFE", category: "Melee" },
  { name: "Stone Hatchet", id: "WEAPON_STONE_HATCHET", category: "Melee" },
  { name: "Smoke Grenade Launcher", id: "WEAPON_GRENADELAUNCHER_SMOKE", category: "Launcher" },
  { name: "Ceramic Pistol", id: "WEAPON_CERAMICPISTOL", category: "Handgun" },
  { name: "Assault Rifle", id: "WEAPON_ASSAULTRIFLE", category: "Assault Rifle" },
  { name: "Pipe Bomb", id: "WEAPON_PIPEBOMB", category: "Thrown" },
  { name: "Micro SMG", id: "WEAPON_MICROSMG", category: "SMG" },
  { name: "Antique Cavalry Dagger", id: "WEAPON_DAGGER", category: "Melee" },
  { name: "Musket", id: "WEAPON_MUSKET", category: "Rifle" },
  { name: "Widowmaker", id: "WEAPON_RAYMINIGUN", category: "Special" },
  { name: "Special Carbine", id: "WEAPON_SPECIALCARBINE", category: "Assault Rifle" },
  { name: "Perico Pistol", id: "WEAPON_GADGETPISTOL", category: "Handgun" },
  { name: "AP Pistol", id: "WEAPON_APPISTOL", category: "Handgun" },
  { name: "Assault Shotgun", id: "WEAPON_ASSAULTSHOTGUN", category: "Shotgun" },
  { name: "Heavy Pistol", id: "WEAPON_HEAVYPISTOL", category: "Handgun" },
  { name: "Homing Launcher", id: "WEAPON_HOMINGLAUNCHER", category: "Launcher" },
  { name: "Pipe Wrench", id: "WEAPON_PIPEWRENCH", category: "Melee" },
  { name: "Marksman Rifle Mk II", id: "WEAPON_MARKSMANRIFLE_MK2", category: "Sniper" },
  { name: "Up-n-Atomizer", id: "WEAPON_RAYPISTOL", category: "Special" },
  { name: "Fire Extinguisher", id: "WEAPON_FIREEXTINGUISHER", category: "Utility" },
  { name: "Minigun", id: "WEAPON_MINIGUN", category: "Machine Gun" },
  { name: "Jerry Can", id: "WEAPON_PETROLCAN", category: "Utility" },
  { name: "Hatchet", id: "WEAPON_HATCHET", category: "Melee" },
  { name: "Double Barrel Shotgun", id: "WEAPON_DBSHOTGUN", category: "Shotgun" },
  { name: "Double-Action Revolver", id: "WEAPON_DOUBLEACTION", category: "Handgun" },
  { name: "Heavy Revolver Mk II", id: "WEAPON_REVOLVER_MK2", category: "Handgun" },
  { name: "Compact Grenade Launcher", id: "WEAPON_COMPACTLAUNCHER", category: "Launcher" },
  { name: "Stun Gun", id: "WEAPON_STUNGUN", category: "Utility" },
  { name: "Bullpup Rifle Mk II", id: "WEAPON_BULLPUPRIFLE_MK2", category: "Assault Rifle" },
  { name: "Switchblade", id: "WEAPON_SWITCHBLADE", category: "Melee" },
  { name: "Sniper Rifle", id: "WEAPON_SNIPERRIFLE", category: "Sniper" },
  { name: "Knuckle Duster", id: "WEAPON_KNUCKLE", category: "Melee" },
  { name: "Special Carbine Mk II", id: "WEAPON_SPECIALCARBINE_MK2", category: "Assault Rifle" },
  { name: "Nightstick", id: "WEAPON_NIGHTSTICK", category: "Melee" },
  { name: "Sawed-Off Shotgun", id: "WEAPON_SAWNOFFSHOTGUN", category: "Shotgun" },
  { name: "Crowbar", id: "WEAPON_CROWBAR", category: "Melee" },
  { name: "Rocket Launcher", id: "WEAPON_RPG", category: "Launcher" },
  { name: "Grenade Launcher", id: "WEAPON_GRENADELAUNCHER", category: "Launcher" },
  { name: "Heavy Sniper", id: "WEAPON_HEAVYSNIPER", category: "Sniper" },
  { name: "Railgun", id: "WEAPON_RAILGUN", category: "Special" },
  { name: "Pistol .50", id: "WEAPON_PISTOL50", category: "Handgun" },
  { name: "SMG", id: "WEAPON_SMG", category: "SMG" },
  { name: "Hammer", id: "WEAPON_HAMMER", category: "Melee" },
  { name: "Pistol", id: "WEAPON_PISTOL", category: "Handgun" },
  { name: "Golf Club", id: "WEAPON_GOLFCLUB", category: "Melee" },
  { name: "SNS Pistol", id: "WEAPON_SNSPISTOL", category: "Handgun" },
  { name: "Carbine Rifle", id: "WEAPON_CARBINERIFLE", category: "Assault Rifle" },
  { name: "Pump Shotgun", id: "WEAPON_PUMPSHOTGUN", category: "Shotgun" },
  { name: "Hazardous Jerry Can", id: "WEAPON_HAZARDCAN", category: "Utility" },
  { name: "Digital Scanner", id: "WEAPON_DIGISCANNER", category: "Utility" },
  { name: "Navy Revolver", id: "WEAPON_NAVYREVOLVER", category: "Handgun" },
  { name: "Tear Gas", id: "WEAPON_SMOKEGRENADE", category: "Thrown" },
  { name: "BZ Gas", id: "WEAPON_BZGAS", category: "Thrown" },
  { name: "Advanced Rifle", id: "WEAPON_ADVANCEDRIFLE", category: "Assault Rifle" },
  { name: "Machete", id: "WEAPON_MACHETE", category: "Melee" },
  { name: "Sticky Bomb", id: "WEAPON_STICKYBOMB", category: "Thrown" },
  { name: "Combat MG Mk II", id: "WEAPON_COMBATMG_MK2", category: "Machine Gun" },
  { name: "Vintage Pistol", id: "WEAPON_VINTAGEPISTOL", category: "Handgun" },
  { name: "MG", id: "WEAPON_MG", category: "Machine Gun" },
  { name: "Flare Gun", id: "WEAPON_FLAREGUN", category: "Utility" }
];